=== altafsamnani/bidx-frontend/wp-content/plugins/bidx-plugin/pages/pages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="data" type="datatype" />

	<xs:complexType name="datatype">
		<xs:sequence>
			<xs:element ref="posttype"/>
			<xs:element ref="description"/>
			<xs:element ref="version"/>
			<xs:element name="posts" type="posts"/>
			<xs:element name="widgets" type="widgets" minOccurs="0"/>
			<xs:element name="menuitems" type="menuitems" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>		

	<xs:element name="posttype" type="xs:string" />
	<xs:element name="description" type="xs:string" />
	<xs:element name="version" type="xs:string" />
	
	<xs:element name="content">
		<xs:annotation>
			<xs:documentation>Content to be filled. Language can be set explicitly although xml:lang could be used?</xs:documentation>
		</xs:annotation>
		<xs:complexType>
		  <xs:simpleContent>
		    <xs:extension base="xs:string">
		      <xs:attribute name="language" type="xs:string" use="optional" />
		    </xs:extension>
		  </xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="title">
		<xs:annotation>
			<xs:documentation>Title. Language can be set explicitly although xml:lang could be used?</xs:documentation>
		</xs:annotation>
		<xs:complexType>
		  <xs:simpleContent>
		    <xs:extension base="xs:string">
		      <xs:attribute name="language" type="xs:string" use="optional" />
		    </xs:extension>
		  </xs:simpleContent>
		</xs:complexType>
	</xs:element>	

	<xs:element name="mapping">
		<xs:annotation>
			<xs:documentation>URL mapping per Language. This is an optional field.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
		  <xs:simpleContent>
		    <xs:extension base="xs:string">
		      <xs:attribute name="language" type="xs:string" use="optional" />
		    </xs:extension>
		  </xs:simpleContent>
		</xs:complexType>
	</xs:element>	
		
	<xs:complexType name="posts">
		<xs:sequence>
			<xs:element name="post" type="post" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>		
	</xs:complexType>

	<xs:complexType name="post">
		<xs:sequence>
			<xs:element name="post_id" type="xs:string"></xs:element>
			<xs:element name="name" type="xs:string"></xs:element>
			<xs:element ref="title" maxOccurs="unbounded"></xs:element>
			<xs:element name="post_date" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Optional a date can be set else load date is added</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element ref="mapping" maxOccurs="unbounded"></xs:element>
			<xs:element name="template" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Optional name of the template in a Theme</xs:documentation>
				</xs:annotation>			
			</xs:element>
			<xs:element name="update" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>If the post already exists should it be updated</xs:documentation>
				</xs:annotation>			
			</xs:element>
			<xs:element ref="content" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="widgets">
		<xs:sequence>
			<xs:element name="widget" type="widget" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="widget">
		<xs:sequence>
			<xs:element name="widget_id" type="xs:string"></xs:element>
			<xs:element name="widget_type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:enumeration value='static' />
					    <xs:enumeration value='dynamic' />
				    </xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="name" type="xs:string"></xs:element>
			<xs:element ref="content" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="menuitems">
		<xs:sequence>
			<xs:element name="menuitem" type="menuitem" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="menuitem">
		<xs:annotation>
			<xs:documentation>Menu items to add</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="menuitem_id" type="xs:string"></xs:element>
			<xs:element name="name" type="xs:string"></xs:element>
			<xs:element name="menuitem_parent" type="xs:string" minOccurs="0"></xs:element>
			<xs:element name="reference" type="xs:string" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== altafsamnani/bidx-frontend/wp-content/plugins/bidx-plugin/pages/page.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./pages.xsd">

	<posttype>page</posttype>
	<description>List of public editable page resources for the enduser to manage</description>
	<version>1.0</version>
	
	<posts>
		<post>
			<post_id>1</post_id>
			<name>TermsofService</name>
			<title>Terms of Service</title>
			<mapping>^termsofservice/?</mapping>
			<update>false</update>
			<content>
				&lt;h2&gt;Terms of service&lt;/h2&gt;
			</content>
		</post>
		<post>
			<post_id>2</post_id>
			<name>Privacy</name>
			<title>Privacy</title>
			<mapping>^privacy/?</mapping>
			<update>false</update>
			<content>
				&lt;h2&gt;Terms of service&lt;/h2&gt;
			</content>
		</post>		
	</posts>
	
</data>

=== altafsamnani/bidx-frontend/wp-content/plugins/bidx-plugin/pages/bidx.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./pages.xsd">

	<posttype>bidx</posttype>
	<description>List of page resources that are hidden for the enduser to manage</description>
	<version>1.0</version>
	
	<posts>
	  	<post>
			<post_id>1</post_id>
			<name>memberlist</name>
			<title>Memberprofile List</title>
			<mapping>^member/?</mapping>
			<content>[bidx app="memberprofile" view="list"]</content>
		</post> 
		<post>
			<post_id>2</post_id>
			<name>member</name>
			<title>Memberprofile</title>
			<mapping>^member/([^/]*)/?</mapping>
			<content>[bidx app="memberprofile"]</content>
		</post>	
		<post>
			<post_id>3</post_id>
			<name>search</name>
			<title>Search</title>
			<mapping>^search/?</mapping>
			<content>[bidx app="search"]</content>
		</post>
		<post>
			<post_id>4</post_id>
			<name>businesslist</name>
			<title>Business List</title>
			<mapping>^business/?</mapping>
			<content>[bidx app="business" view="list"]</content>
		</post>	
		<post>
			<post_id>5</post_id>
			<name>business</name>
			<title>Business</title>
			<mapping>^business/([^/]*)/?</mapping>
			<content>[bidx app="business"]</content>
		</post>	
		<post>
			<post_id>6</post_id>
			<name>group</name>
			<title>Last Members</title>
			<mapping>^group/lastmembers?</mapping>
			<content>[bidx app="group" view="lastMembers"]</content>
		</post>	
		<post>
			<post_id>6</post_id>
			<name>groupinfo</name>
			<title>Group Information</title>
			<mapping>^group/groupinfo?</mapping>
			<content>[bidx app="group" view="getGroupDetails"]</content>
		</post>											
	</posts>
	
	<widgets>
		<widget>
			<widget_id>last_members_of_group</widget_id>
			<widget_type>static</widget_type>
			<name>Latest Members Of Group</name>
			<content></content>
		</widget>
		<widget>
			<widget_id>group_info</widget_id>
			<widget_type>static</widget_type>
			<name>Group Information</name>
			<content></content>
		</widget>
		<widget>
			<widget_id>last_business_of_group</widget_id>
			<widget_type>static</widget_type>
			<name>Latest Businesses</name>
			<content></content>
		</widget>				
	</widgets>
	
</data>
